#ifndef PRIME_PRACTICE_NATIVE_SETTINGSMENU_HPP
#define PRIME_PRACTICE_NATIVE_SETTINGSMENU_HPP


#include "utils.hpp"

namespace GUI {
  void drawSettingsMenu();
}


#endif //PRIME_PRACTICE_NATIVE_SETTINGSMENU_HPP
