#ifndef PRIME_PRACTICE_NATIVE_WORLDRENDERER_HPP
#define PRIME_PRACTICE_NATIVE_WORLDRENDERER_HPP


namespace WorldRenderer {
  void RenderWorld();
};


#endif //PRIME_PRACTICE_NATIVE_WORLDRENDERER_HPP
