#ifndef PRIME_PRACTICE_NATIVE_CARCHITECTUREQUEUE_HPP
#define PRIME_PRACTICE_NATIVE_CARCHITECTUREQUEUE_HPP

class CArchitectureQueue {
public:
    PADDING(8);

};

#endif //PRIME_PRACTICE_NATIVE_CARCHITECTUREQUEUE_HPP
