#include "prime/CEntity.hpp"

VTableInfo MP1_VTABLES[VTABLE_COUNT] = {
    {.vtable = 0x803d9660, .name = "CFirstPersonCamera", .isActor = true},
    {.vtable = 0x803d96e8, .name = "CPlayer", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803da450, .name = "CScriptActor", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803da4d8, .name = "CScriptTrigger", .isActor = true},
    {.vtable = 0x803da558, .name = "CScriptWaypoint", .isActor = true},
    {.vtable = 0x803daa78, .name = "CScriptDoor", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803dab90, .name = "CBallCamera", .isActor = true},
    {.vtable = 0x803dac38, .name = "CScriptEffect", .isActor = true},
    {.vtable = 0x803dadd8, .name = "CScriptTimer"},
    {.vtable = 0x803df128, .name = "CScriptSound", .isActor = true},
    {.vtable = 0x803df220, .name = "CScriptPlatform", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803df328, .name = "CScriptGenerator"},
    {.vtable = 0x803df348, .name = "CScriptCameraWaypoint", .isActor = true},
    {.vtable = 0x803df3b8, .name = "CGameLight", .isActor = true},
    {.vtable = 0x803df4f8, .name = "CScriptPickup", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803df580, .name = "CScriptDock", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803df688, .name = "CScriptCameraHint", .isActor = true},
    {.vtable = 0x803df830, .name = "CScriptRelay"},
    {.vtable = 0x803df850, .name = "CScriptSpawnPoint"},
    {.vtable = 0x803df890, .name = "CBeetle", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803dfbf0, .name = "CScriptHUDMemo"},
    {.vtable = 0x803dfd08, .name = "CScriptDamageableTrigger", .isActor = true},
    {.vtable = 0x803dfd78, .name = "CScriptDebris", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e02c8, .name = "CScriptSpiderBallWaypoint", .isActor = true},
    {.vtable = 0x803e0bf8, .name = "CScriptCoverPoint", .isActor = true},
    {.vtable = 0x803e0c68, .name = "CPathCamera", .isActor = true},
    {.vtable = 0x803e0d70, .name = "CHUDBillboardEffect", .isActor = true},
    {.vtable = 0x803e2b68, .name = "CScriptSpecialFunction", .isActor = true},
    {.vtable = 0x803e3004, .name = "CParasite", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e32d8, .name = "CScriptPlayerHint", .isActor = true},
    {.vtable = 0x803e3618, .name = "CScriptPickupGenerator"},
    {.vtable = 0x803e3638, .name = "CScriptPointOfInterest", .isActor = true},
    {.vtable = 0x803e4708, .name = "CScriptRoomAcoustics"},
    {.vtable = 0x803e4b18, .name = "CCollisionActor", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e7068, .name = "CScriptStreamedMusic"},
    {.vtable = 0x803e8558, .name = "CTeamAiMgr"},
    {.vtable = 0x803e86e8, .name = "CScriptMemoryRelay"},
    {.vtable = 0x803e9d80, .name = "CInterpolationCamera", .isActor = true},
    {.vtable = 0x803dadf8, .name = "CCinematicCamera", .isActor = true},
    {.vtable = 0x803daef0, .name = "CScriptCounter"},
    {.vtable = 0x803dfc80, .name = "CScriptCameraFilterKeyframe"},
    {.vtable = 0x803dfca0, .name = "CScriptCameraBlurKeyframe"},
    {.vtable = 0x803dfe00, .name = "CScriptCameraShaker"},
    {.vtable = 0x803dfe20, .name = "CScriptActorKeyframe"},
    {.vtable = 0x803dfe70, .name = "CScriptWater", .isActor = true},
    {.vtable = 0x803e27b0, .name = "CScriptDistanceFog"},
    {.vtable = 0x803e2d28, .name = "CSpankWeed", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e3e80, .name = "CScriptBallTrigger", .isActor = true},
    {.vtable = 0x803e4be0, .name = "CScriptPlayerActor", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e4d08, .name = "CFlaahgraRenderer", .isActor = true},
    {.vtable = 0x803e4e88, .name = "CFlaahgra", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e52f8, .name = "CScriptAreaAttributes"},
    {.vtable = 0x803e5830, .name = "CScriptVisorFlare", .isActor = true},
    {.vtable = 0x803e5c40, .name = "CScriptSwitch"},
    {.vtable = 0x803e6408, .name = "CFlaahgraTentacle", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e8578, .name = "CSnakeWeedSwarm", .isActor = true},
    {.vtable = 0x803e8670, .name = "CScriptSpindleCamera", .isActor = true},
    {.vtable = 0x803d9e30, .name = "CEntity"},
    {.vtable = 0x803d9eb0, .name = "CActor", .isActor = true},
    {.vtable = 0x803da0a8, .name = "CExplosion", .isActor = true},
    {.vtable = 0x803da5c8, .name = "CPatterned", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803dacc0, .name = "CBomb", .isActor = true},
    {.vtable = 0x803df870, .name = "CScriptRandomRelay"},
    {.vtable = 0x803e0800, .name = "CSpacePirate", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e0d00, .name = "CScriptGrapplePoint", .isActor = true},
    {.vtable = 0x803e2808, .name = "CPowerBomb", .isActor = true},
    {.vtable = 0x803e2d08, .name = "CScriptActorRotate"},
    {.vtable = 0x803e3da8, .name = "CScriptSteam", .isActor = true},
    {.vtable = 0x803e3e28, .name = "CScriptRipple"},
    {.vtable = 0x803e3f00, .name = "CPlasmaProjectile", .isActor = true},
    {.vtable = 0x803e4018, .name = "CNewIntroBoss", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e4330, .name = "CScriptTargetingPoint", .isActor = true},
    {.vtable = 0x803e51e8, .name = "CIceImpact", .isActor = true},
    {.vtable = 0x803e5318, .name = "CWaveBuster", .isActor = true},
    {.vtable = 0x803e5758, .name = "CFishCloud", .isActor = true},
    {.vtable = 0x803e58a0, .name = "CScriptWorldTeleporter"},
    {.vtable = 0x803e58c0, .name = "CScriptVisorGoo", .isActor = true},
    {.vtable = 0x803e5c20, .name = "CScriptControllerAction"},
    {.vtable = 0x803e6308, .name = "CWallCrawlerSwarm", .isActor = true},
    {.vtable = 0x803e6bb0, .name = "CScriptColorModulate"},
    {.vtable = 0x803e7048, .name = "CScriptMidi"},
    {.vtable = 0x803e7158, .name = "CEnergyProjectile", .isActor = true},
    {.vtable = 0x803e71ec, .name = "CScriptGunTurret", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e7a70, .name = "CScriptCameraPitchVolume", .isActor = true},
    {.vtable = 0x803e8c40, .name = "CScriptCameraHintTrigger", .isActor = true},
    {.vtable = 0x803e9d10, .name = "CNewFlameThrower", .isActor = true},
    {.vtable = 0x803dff90, .name = "CWarWasp", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e1918, .name = "CChozoGhost", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e5154, .name = "CFlaahgraProjectile", .isActor = true},
    {.vtable = 0x803e88a8, .name = "CAtomicAlpha", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e8cb0, .name = "CAmbientAI", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e9258, .name = "CRidley", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e96c0, .name = "CPuffer", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e9e10, .name = "CSeedling", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803ed508,
     .name = "IAnimReader"}, // also possibly CAnimSourceReader or CAnimTreeNode or CFBStreamedAnimReader
    {.vtable = 0x803e1c88, .name = "CFireFlea", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e2878, .name = "CMetaree", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e3348, .name = "CRipper", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e3ad8, .name = "CMetroid", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e45d8, .name = "CFlameThrower", .isActor = true},
    {.vtable = 0x803e4728, .name = "CIceSheegoth", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e57c4, .name = "CFishCloudModifier", .isActor = true},
    {.vtable = 0x803e5954, .name = "CJellyZap", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e5ce0, .name = "CThardus", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e6074, .name = "CDestroyableRock", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e6398, .name = "CScriptAiJumpPoint", .isActor = true},
    {.vtable = 0x803e685c, .name = "CFlyingPirate", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e6be0,
     .name = "CThardusRockProjectile",
     .isActor = true,
     .isPhysicsActor = true,
     .isPatterned = true},
    {.vtable = 0x803e70e8, .name = "CRepulsor", .isActor = true},
    {.vtable = 0x803e7350, .name = "CBabygoth", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e774c, .name = "CEyeBall", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e80c0, .name = "CRipperControlledPlatform", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e8240, .name = "CMagdolite", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e8e4c, .name = "CAtomicBeta", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e9118, .name = "CElectricBeamProjectile", .isActor = true},
    {.vtable = 0x803e9990, .name = "CFire", .isActor = true},
    {.vtable = 0x803e9a40, .name = "CTryclops", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803ea7c4, .name = "CBurrower", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e36a8, .name = "CDrone", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e3a58, .name = "CDroneLaser", .isActor = true},
    {.vtable = 0x803e4400, .name = "CScriptEMPulse", .isActor = true},
    {.vtable = 0x803e5388, .name = "CMetroidBeta", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e5cc0, .name = "CScriptPlayerStateChange"},
    {.vtable = 0x803e6778, .name = "CIceAttackProjectile", .isActor = true},
    {.vtable = 0x803e7ae0, .name = "CElitePirate", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803e7f58, .name = "CGrenadeLauncher", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803e8050, .name = "CShockWave", .isActor = true},
    {.vtable = 0x803ead54, .name = "CMetroidPrimeExo", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803eb0fc, .name = "CMetroidPrimeExoPhysicsDummy", .isActor = true, .isPhysicsActor = true},
    {.vtable = 0x803eb180, .name = "CScriptBeam", .isActor = true},
    {.vtable = 0x803eb244,
     .name = "CMetroidPrimeEssence",
     .isActor = true,
     .isPhysicsActor = true,
     .isPatterned = true},
    {.vtable = 0x803eb638, .name = "CMetroidPrimeRelay"},
    {.vtable = 0x803eb658, .name = "CScriptMazeNode", .isActor = true},
    {.vtable = 0x803eb6c8, .name = "CFlash", .isActor = true},
    {.vtable = 0x803eb868, .name = "COmegaPirate", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
    {.vtable = 0x803ebb48, .name = "CPhazonPool", .isActor = true},
    {.vtable = 0x803ebc70,
     .name = "CPhazonHealingNodule",
     .isActor = true,
     .isPhysicsActor = true,
     .isPatterned = true},
    {.vtable = 0x803ec030, .name = "CScriptShadowProjector", .isActor = true},
    {.vtable = 0x803ec0a0, .name = "CEnergyBall", .isActor = true, .isPhysicsActor = true, .isPatterned = true},
};
