#pragma once

#define HOOK_FRAME_SIZE 432
#define HOOK_REGS_OFFSET 8

#define HOOK_REG_GPR_OFFSET 0
#define HOOK_REG_LR_OFFSET 128
#define HOOK_REG_CR_OFFSET 132
#define HOOK_REG_CTR_OFFSET 136
#define HOOK_REG_XER_OFFSET 140
#define HOOK_REG_FPR_OFFSET 152
#define HOOK_REG_EARLY_RET_OFFSET 408

#define HOOK_CTX_HOOK_OFFSET 0
#define HOOK_CTX_TRAMP_OFFSET 4
