#ifndef PRIME_PRACTICE_NATIVE_STRIGGERRENDERCONFIG_HPP
#define PRIME_PRACTICE_NATIVE_STRIGGERRENDERCONFIG_HPP

struct STriggerRenderConfig {
public:

};

#endif //PRIME_PRACTICE_NATIVE_STRIGGERRENDERCONFIG_HPP
