name: Build pyinstaller for windows

on:
  workflow_dispatch:

jobs:
  build_installer:
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run pyinstaller
        run: |
          pip install PyInstaller
          cd patcher
          pyinstaller --onefile main.py
        
      - uses: actions/upload-artifact@v3
        with:
          name: main.exe
          path: patcher/dist/main.exe
          if-no-files-found: error
